name: MoonBit CLI Check

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Moon env
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc libssl-dev
          curl -fsSL https://cli.moonbitlang.com/install/unix.sh | bash
          echo "$HOME/.moon/bin" >> "$GITHUB_PATH"
      - name: Moon Check
        run: |
          moon fmt --check
          moon check --deny-warn
          moon info
          git diff --exit-code
      - name: Moon Test
        run: moon test --deny-warn
